# Generated by Django 4.1.3 on 2022-12-23 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comments_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='author',
        ),
        migrations.AddField(
            model_name='bids',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
